# Generated by Django 3.0.5 on 2021-09-14 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_endpoint', models.CharField(max_length=300)),
                ('original_question', models.TextField(null=True)),
                ('original_title', models.CharField(max_length=200, null=True)),
                ('translated_title', models.CharField(max_length=200, null=True)),
                ('translated_question', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questioner', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Question')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerer', models.CharField(max_length=50, null=True)),
                ('original_answer', models.TextField(null=True)),
                ('translated_answer', models.TextField(null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Question')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
    ]
