# Generated by Django 3.0.5 on 2021-09-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210917_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_endpoint',
            field=models.CharField(max_length=1000),
        ),
    ]
