# Generated by Django 3.0.5 on 2021-09-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210917_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
