# Generated by Django 3.0.5 on 2021-09-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_question_asked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=20)),
                ('limit', models.IntegerField()),
                ('last_finish', models.IntegerField()),
            ],
            options={
                'db_table': 'standards',
            },
        ),
    ]
