# Generated by Django 3.0.5 on 2021-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='today_did',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
