# Generated by Django 3.0.5 on 2021-10-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210928_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='last_finish',
            new_name='last_finish_ko',
        ),
    ]
