# Generated by Django 3.0.5 on 2021-10-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211004_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='last_finish_en',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
