# Generated by Django 3.0.5 on 2021-10-05 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_standard_last_finish_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='day_history',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 12, 12, 12, 200000, tzinfo=utc), null=True),
        ),
    ]
