# Generated by Django 3.0.5 on 2021-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211005_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.CharField(max_length=50)),
                ('blg_name', models.CharField(max_length=100, null=True)),
                ('call_back_url', models.URLField(null=True)),
                ('app_id', models.CharField(max_length=200, null=True)),
                ('blog_id', models.CharField(max_length=100, null=True)),
                ('secret_key', models.CharField(max_length=200, null=True)),
                ('client_secret', models.CharField(max_length=200, null=True)),
                ('token_type', models.CharField(max_length=20, null=True)),
                ('client_id', models.CharField(max_length=100, null=True)),
                ('access_token', models.CharField(max_length=200, null=True)),
                ('refresh_token', models.CharField(max_length=200, null=True)),
                ('api_key', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'configurations',
            },
        ),
    ]
