# Generated by Django 3.0.5 on 2021-10-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
