# Generated by Django 3.0.5 on 2021-10-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_configuration_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='blg_name',
            new_name='blog_name',
        ),
    ]
